# Global Values
repo_url: "https://github.com/bitbuy-infrastructure/argocd-infra-deployment.git"
region: ""
account: ""
clusterName: ""

# AWS CloudWatch Metrics Values
awsCloudWatchMetrics:
  enable: false

# AWS for Fluent Bit Values
awsForFluentBit:
  enable: false
  serviceAccount:
    name:
    create: true
  logGroupName:
  firehose:
    enabled: false
  kinesis:
    enabled: false
  elasticsearch:
    enabled: false

# Metrics Server Values
metricsServer:
  enable: false
