{{- if and (.Values.awsForFluentBit) (.Values.awsForFluentBit.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-for-fluent-bit
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repo_url }}
    path: add-ons/aws-for-fluent-bit
    targetRevision: HEAD
    helm:
      parameters:
      - name: aws-for-fluent-bit.cloudWatch.region
        value: {{ .Values.region }}
      - name: aws-for-fluent-bit.serviceAccount.name
        value: {{ .Values.awsForFluentBit.serviceAccountName }}
      - namle: aws-for-fluent-bit.serviceAccount.create
        value: {{ .Values.awsForFluentBit.serviceAccountName.create }}
      - name: aws-for-fluent-bit.cloudWatch.serviceAccount.name
        value: {{ .Values.awsForFluentBit.serviceAccountName }}
      - name: aws-for-fluent-bit.cloudWatch.logGroupName
        value: {{ .Values.awsForFluentBit.logGroupName }}
      - name: aws-for-fluent-bit.firehose.enabled
        value: {{ .Values.awsForFluentBit.firehose.enabled }}
      - name: aws-for-fluent-bit.firehose.region
        value: {{ .Values.region }}
      - name: aws-for-fluent-bit.kinesis.enabled
        value: {{ .Values.awsForFluentBit.kinesis.enabled }}
      - name: aws-for-fluent-bit.kinesis.region
        value: {{ .Values.region }}
      - name: aws-for-fluent-bit.elasticsearch.enabled
        value: {{ .Values.awsForFluentBit.elasticsearch.enabled }}
      - name: aws-for-fluent-bit.elasticsearch.region
        value: {{ .Values.region }}
  destination:
    server: https://kubernetes.default.svc
    {{ if .Values.awsForFluentBit.namesapce }}
    namespace: {{ .Values.awsForFluentBit.namesapce }}
    {{ else }}
    namespace: kube-system
    {{ end }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
