{{- if and (.Values.postgresql) (.Values.postgresql.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repo_url }}
    path: add-ons/postgresql
    targetRevision: HEAD
    helm:
      parameters:
        - name: postgresql.auth.existingSecret
          value: {{ .Values.postgresql.secretName }}
        - name: postgresql.image.tag
          value: {{ .Values.postgresql.imageTag }}
  destination:
    server: https://kubernetes.default.svc
    {{ if .Values.postgresql.namespace }}
    namespace: {{ .Values.postgresql.namespace }}
    {{ else }}
    namespace: postgresql
    {{ end }}
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  {{- end -}}
