# https://github.com/hashicorp/vault-helm/blob/main/values.yaml
# https://www.vaultproject.io/docs/configuration/seal/awskms
---
vault:
  server:
    ingress:
      enabled: true
      hosts:
        - host: ""
          paths: []
    ui:
      enabled: true
      serviceType: ClusterIP
    serviceAccount:
      name: vault
    ha:
      enabled: true
      replicas: 3
      raft:

        # Enables Raft integrated storage
        enabled: true
        # Set the Node Raft ID to the name of the pod
        setNodeId: false

        # Note: Configuration files are stored in ConfigMaps so sensitive data
        # such as passwords should be either mounted through extraSecretEnvironmentVars
        # or through a Kube secret.  For more information see:
        # https://www.vaultproject.io/docs/platform/k8s/helm/run#protecting-sensitive-vault-configurations
        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "raft" {
            path = "/vault/data"
          }
          service_registration "kubernetes" {}
          # seal "awskms" {
          #   kms_key_id = ${VAULT_AWSKMS_SEAL_KEY_ID}
          # }

    extraEnvironmentVars:
      AWS_REGION: "" # this should be passed in from TF -> Argo CD
      VAULT_SEAL_TYPE: ""
      VAULT_AWSKMS_SEAL_KEY_ID: ""
