apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m4.large", "m5.large", "m5.2xlarge"]
  limits:
    resources:
      cpu: 100
  provider:
    instanceProfile: "aws005-jmctest-teod-eks-managed-ondemand" # self-managed IAM Instance profile Name
    subnetSelector:
      Name: "*aws005-jmctest-teod-vpc-private*"
    securityGroupSelector:
      Name: "*aws005-jmctest-teod-eks*"
  ttlSecondsAfterEmpty: 30
