---
# https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/values.yaml
aws-for-fluent-bit:
  global:
  ## Override the deployment namespace
    namespaceOverride: logging

  serviceAccount:
    create: false
    name: ""

  cloudWatch:
    enable: true
    region: ""
    logGroupName: ""

  firehose:
    enable: false
    region: ""

  kinesis:
    enable: false
    region: ""

  elasticsearch:
    enable: false
    region: ""
