---
# https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/values.yaml
aws-for-fluent-bit:
  global:
  ## Override the deployment namespace
    namespaceOverride: logging

  serviceAccount:
    create: false
    name: ""

  cloudWatch:
    enable: true
    region: ""
    logGroupName: ""

  firehose:
    enable: false
    region: ""

  kinesis:
    enable: false
    region: ""

  elasticsearch:
    enable: false
    region: ""

#  extraParsers: {}

# example:
  extraParsers: |
    [PARSER]
        Name   logfmt
        Format logfmt

# example:
# extraInputs: |
#   [INPUT]
#       Name         winlog
#       Channels     Setup,Windows PowerShell
#       Interval_Sec 1
#       DB           winlog.sqlite

  extraInputs: |
    [INPUT]
        Name systemd
        Tag host.*.${NODE_NAME}
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

# example:
# extraFilters: |
#   [FILTER]
#       Name   grep
#       Match  *
#       Exclude log lvl=debug*
  extraFilters: |
    # [FILTER]
    #     Name         parser
    #     Match        kube.*
    #     Key_Name     log
    #     Reserve_Data True
    #     Parser       glog
    #     Parser       ingress-nginx-controller
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
    [FILTER]
        Name        modify
        Match   *
        Rename log message
    # [FILTER]
    #     Name    lua
    #     Match   kube.*
    #     script  /fluent-bit/scripts/set_labels.lua
    #     call    set_labels
    [FILTER]
        # Re: BBSECAWS-221, also see: https://bitbuy.atlassian.net/l/c/p3AboJs2
        Name rewrite_tag
        Match kube.*
        Rule $_aws['CloudWatchMetrics'][0]['Namespace'] (.*) cwmetric.$1 true
        ## https://docs.fluentbit.io/manual/pipeline/outputs

# example:
# extraOutputs: |
#   [OUTPUT]
#     Name file
#     Format template
#     Template {time} used={Mem.used} free={Mem.free} total={Mem.total}

extraOutputs: |
    [OUTPUT]
        # Re: BBSECAWS-221, also see: https://bitbuy.atlassian.net/l/c/p3AboJs2
        Name cloudwatch_logs
        Match cwmetric.*
        log_format json/emf
        log_stream_name bb-metrics
        log_group_name bb-metrics
        auto_create_group true
