name: ci-helm-non-prod

# when to run the this workflow
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  ci-helm-non-prod:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      -
        name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.0
      # https://github.com/helm/chart-testing/blob/main/doc/ct_lint.md
      -
        name: Run chart-testing (list-changed)
        id: helm-list-changed
        run: |
          changed=$(ct list-changed --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      # TODO make this more dymamic
      -
        name: Run chart-testing (lint)
        id: helm-lint
        run: |
          ct lint --chart-dirs helm/ --debug --target-branch main --config testing/helm/ct.yaml
